##################################################################################
# Cloudify OpenStack built in types and plugins definitions.
##################################################################################

plugins:
  openstack_adds:
    executor: central_deployment_agent
    source: https://github.com/boucherv-orange/cloudify-openstack-adds-plugin/archive/master.zip
    package_name: cloudify-openstack-adds-plugin
    package_version: '1.4'

node_types:
  cloudify.openstack_adds.nodes.DNS_client:
    derived_from: cloudify.nodes.Compute
    properties:
      dns_ips:
        default: []
      domains:
        default: []
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: openstack_adds.designate_plugin.zones.add_zones
        delete:
          implementation: openstack_adds.designate_plugin.zones.del_zones

  cloudify.openstack_adds.nodes.Subnet:
    derived_from: cloudify.nodes.Subnet
    properties:
      subnet:
        default: {}
      use_external_resource:
        type: boolean
        default: false
      resource_id:
        default: ''
      openstack_config:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: openstack_adds.neutron_plugin.subnet.create
          inputs:
            args:
              default: {}
            openstack_config:
              default: {}
        delete:
          implementation: openstack_adds.neutron_plugin.subnet.delete
          inputs:
            openstack_config:
              default: {}
      cloudify.interfaces.validation:
        creation:
          implementation: openstack_adds.neutron_plugin.subnet.creation_validation
          inputs:
            args:
              default: {}
            openstack_config:
              default: {}

relationships:
  cloudify.openstack_adds.node_connected_to_DNS:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish:
          implementation: openstack_adds.designate_plugin.recordsets.add_node
          executor: central_deployment_agent
          inputs:
            domain:
              default: exemple.com
            record_ip:
              default: ""
            other_roles: 
              default: []
            other_records:
              default: []
        unlink:
          implementation: openstack_adds.designate_plugin.recordsets.del_node
          executor: central_deployment_agent
          inputs:
            domain:
              default: exemple.com
            record_ip:
              default: ""
            other_roles: 
              default: []
            other_records:
              default: []
